### ISSUE TITLE
Remove symfony/framework-bundle from require-dev

### ISSUE THREAD

**Issue by bnymn** [Elao/PhpEnums#118]
Hi there,

I have just realized that your package does not really need symfony/framework-bundle. Can we please remove it?

I am using this package in my bundle, and I get the following error message when I run my tests.

```
Symfony\Component\Config\Definition\Exception\InvalidConfigurationException : The child node "resource" at path "framework.router" must be configured.
```

```
"name": "symfony/framework-bundle",
"version": "v4.4.0",
```

**Comment by ogizanagi** [comment]
Hi @bnymn 

I think there is a misunderstanding here. As you can see in your PR, the tests are failing. This is because the Framework bundle is used in integration test to check all the features related to Symfony and the bundle are properly working. Tests are even booting a Symfony app using the FrameworkBundle. So this dependency IS required for us.

Now regarding your issue, note that the `symfony/framework-bundle` dependency is in our `require-dev` section of `composer.json`. This means these dependencies are not installed when you require `elao/enum` in **your** project or bundle. These dependencies are only installed whenever you fork the project locally and run `composer install/update` to dev and run tests of this repository.

I'm unsure why you get this issue. But I really suspect this is not related to the require-dev dependencies of `elao/enum`. So I'm gonna close your PR for now.
