### ISSUE TITLE
QueryBuilder can not convert enum object

### ISSUE THREAD

**Issue by piotrp321** [Elao/PhpEnums#129]
I Have a enum 

![image](https://user-images.githubusercontent.com/10939014/119183011-ca1f8200-ba73-11eb-8ecd-336e94c0a921.png)

Doctrine config

![image](https://user-images.githubusercontent.com/10939014/119183070-e02d4280-ba73-11eb-9fd1-41ee8a59cb44.png)

QueryBuilder 
![image](https://user-images.githubusercontent.com/10939014/119183129-f3401280-ba73-11eb-9230-cb659fef6142.png)

And the result of this is a error : Object of class App\Enum\Backup\BackupStatus could not be converted to string

This is not supported or am I doing something wrong?

**Comment by ogizanagi** [comment]
Hello. thank you for opening this issue.
Actually it's well known and I should have added an entry in the documentation...

When using the QueryBuilder and `->setParameter`, Doctrine is unable to determine that the type of the parameter is supposed to match the property (here `c.status`), since you can actually use this parameter anywhere in the query. So Doctrine won't fetch the metadata to get it's an enum, and won't convert it using the DBAL type.

Instead, you must use the raw value of the enum, e.g: `BackupStatus::SUCCESS` (without `()`).

Note that magic methods such as `->findBy(['status' => BackupStatus::SUCCESS()])` work, because in such case Doctrine can clearly identify the intent and get the `status` property metadata to convert the enum.

**Comment by piotrp321** [comment]
that is a bit strange. As I had myclubs/enum to querybuilder working with them

**Comment by ogizanagi** [comment]
Really? Using https://github.com/acelaya/doctrine-enum-type? Maybe there is something I'm unaware of. 🤔  
Are you sure you were setting the enum instance as parameter, not the enum value?

**Comment by ogizanagi** [comment]
Actually I think your instance was simply converted to a string, e.g, the raw value: https://github.com/myclabs/php-enum/blob/af4b5622434b2e129c28fab6d1a5bab436070e88/src/Enum.php#L133-L136

We don't implement the `__toString` method on basic enum. We do only for readable enum, for which it is meant to return the human readable value / translation key, not the raw one.
