### ISSUE TITLE
__tostring in basic abstract enum 

### ISSUE THREAD

**Issue by mvrhov** [Elao/PhpEnums#27]
Could we add tostring method into the abstract enum. This means that the default value would be returned as string. And not a mapping as in case of a readable enum.

_looking at the component an seeing whats missing here and my own implementation has._

**Comment by ogizanagi** [comment]
First of all, thanks for your suggestion.
I won't provide a `__toString()` method in the base `Enum` class, because of the following reasons:

1. An enum value isn't always a string. It can be an integer, and it won't make sense to cast it blindly to a string.
1. An enum value shouldn't matter much in an application, and casting it to string thus doesn't seem to be a relevant need to me. In other languages providing native enumerated types support, the enum value is usually optional, generated and hidden to the end-user. The enum is then used as an well identified "symbol".
1. It'll make the behavior different between a readable enum and a non-readable enum. The `__toString()` method really makes sense for a readable one, but not particularly for a non-readable one.

**Comment by mvrhov** [comment]
In those languages e.g C I can simply cast integer into an enum, or write it into a file.
Casting it into the string can also hel if you use some other db access as the DBAL. e.g plain php functions or plain pdo.

**Comment by ogizanagi** [comment]
Closing as "Won't fix" for the reasons explained above.
