### ISSUE TITLE
Wrong trait conflict resolution in SimpleChoiceEnum

### ISSUE THREAD

**Issue by jonagoldman** [Elao/PhpEnums#91]
Extending SimpleChoiceEnum without implementing the `choices()` method will result in a PhpCsFixer alert message:

```
'App\MyEmum' does not implement method 'choices'
```

The issue seems to be that `choices()` is declared as `protected` and visibility is not resolved in trait conflict resolution.

Submitting pull request.

**Comment by ogizanagi** [comment]
Hi @jonagoldman , thank you for the report and trying to fix the issue.

Bu I don't really get what's the issue here. This [project runs PhpCsFixer on CI](https://travis-ci.org/github/Elao/PhpEnums/jobs/707597995#L366) and no such warning was emitted. ([we have some tests extending `SimpleChoiceEnum` without overriding `choices`](https://github.com/Elao/PhpEnums/blob/8be5c302e635545e59013d83a9aa68978829c70f/tests/Unit/SimpleChoiceEnumTest.php#L39) that would have triggered it).
I'm not even aware of PhpCsFixer triggering such warnings. Did you mean Php Code Sniffer instead?

Both
https://github.com/Elao/PhpEnums/blob/8be5c302e635545e59013d83a9aa68978829c70f/src/ChoiceEnumTrait.php#L60

and 
https://github.com/Elao/PhpEnums/blob/8be5c302e635545e59013d83a9aa68978829c70f/src/AutoDiscoveredValuesTrait.php#L39

have the same protected visibility, so I don't see any issue.

**Comment by jonagoldman** [comment]
Hi @ogizanagi ,
you are right, the message is from CodeSniffer not CSFixer,
so I guess my question is: the method is defined as `protected` in the trait, but the example in the readme file overrides it as `public`:

https://github.com/Elao/PhpEnums/blob/c0b27266a94404db172055006c663472ec81afb8/README.md#L311

This is valid because the method is not defined in an interface, but is this intentional?

**Comment by ogizanagi** [comment]
No, it was meant to be protected as well here.

**Comment by jonagoldman** [comment]
Ok, sorry for this long message just one last thing I couldn't find in the PHP docs:

A trait can implement a method defined in another trait. This generally happen when one trait is one class and the implementing trait is in a class that extends that class.

But in this case both traits are in the same class and the "supposed" conflict is not explicitly resolved, so maybe that's why I'm getting the message from CodeSniffer.

It's not explicit that the implementation method should be used instead of the definition.

So does PHP understands the desired result and CodeSniffer is wrong?
Or just by chance PHP decides the right order and this could be an issue in other scenarios or different/future PHP versions?

Thanks.

**Comment by ogizanagi** [comment]
> It's not explicit that the implementation method should be used instead of the definition.

There is no such thing as a conflict between an abstract method (contract) and an implementation. 
`ChoiceEnumTrait` declares a dependency to a `choices` contract, by using an abstract method. Anybody can implement it; either it is the class using the, another class in the hierarchy, or even another trait (it doesn't even matter it comes from a trait for PHP, it's as it was copy/pasted to the class using the trait).

The only conflict can happen by using two traits on the same class defining both a `choices` implementation. This conflict is resolved explicitly by using `insteadof` to favor an implementation over another. (that's what happen with https://github.com/Elao/PhpEnums/blob/8be5c302e635545e59013d83a9aa68978829c70f/src/SimpleChoiceEnum.php#L24 for instance)

See https://3v4l.org/SHGiF

**Comment by jonagoldman** [comment]
I see, I knew about the two traits, same method, same class conflict, but was confused by the definition vs implementation case.

Thanks for clarifying that!
I guess I can close the issue now.

Appreciate you taking the time to explain!
